name: Deployment Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: SCP Deploy
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_SERVER }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "site/*"
          target: "/var/www/html/demo-php-cicd"
        